### ISSUE TITLE
move router to core?

### ISSUE THREAD

**Issue by fleg** [node-ci/nci-rest-api-server#1]
What about move http router to core and make public api? It will simplify plugins development

**Comment by okv** [comment]
I see your point. I thought about that but in general case so many plugins can be done with different needs (e.g. when you're building ui you want to omit some fields and do not pass them to the client or sort fields in specific order then offset and limit, etc). So currently there two options: build own api (using public internal interface) or depend on existing api plugins (not as npm dependency but provide specific information on plugin's page - e.g. some ui plugin may tell that you need to install and configure not only it but also some api plugin (nci-rest-api-server for example)).

Core http api also should be super stable and should provide fallbacks for breaking changes. Thus it's not so simple to implement great api which is suitable for all needs (especially when you don't have sophisticated db query language =).

**Comment by fleg** [comment]
I talking only about http router api.
Currently if I develop plugin that using http, I should write url matching logic, like this:

``` js
req.url.match(/^\/webhooks\/([\-\w]+)\/github\/(.+)/);
```

and body parsing like this:

``` js
req.setEncoding('utf-8');
var bodyString = '';
req.on('data', function(data) {
    bodyString += data;
});
req.on('end', function() {
    var body = bodyString ? JSON.parse(bodyString) : {};
});
```

So, I suggest move [this](https://github.com/node-ci/nci-rest-api-server/blob/master/lib/index.js#L10-L48)  and [this](https://github.com/node-ci/nci-rest-api-server/blob/master/lib/index.js#L206-L245) code to core and use it in all plugins, instead of implementing it again and again in each new plugin that using http.

ps. maybe use express.js?

**Comment by okv** [comment]
Oh I see, it's supposed that you could use your favorite router when writing plugins for nci (e.g. express, restify, etc).

p.s. I have plans (but don't have time) to move nci-rest-api-server to express + add tests.

**Comment by fleg** [comment]
ok
